name: BigDL Core Release Pypi

on:
#  pull_request:
#    branchs: [ main ] 
  workflow_dispatch:
    inputs:
      branch:
        description: 'bigdl core branch (e.g. master, branch-2.1)'
        required: true
        default: 'master'
        type: string
      version:
        description: 'pypi version (e.g. 2.1.0, 2.2.0b20220927)'
        required: true
        default: '2.2.0b20221206'
        type: string
      jarurl:
        description: 'jar url (e.g. https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/core/dist/all/2.2.0-SNAPSHOT/all-2.2.0-20220919.010507-1.jar)'
        required: true
        default: 'https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/core/dist/all/2.2.0-SNAPSHOT/all-2.2.0-20220919.010507-1.jar'
        type: string

env:
  Branch: ${{ github.event.inputs.branch }}

permissions:
  contents: read

jobs:
  llm-cpp-build:
    uses: ./.github/workflows/llm-binary-build.yml
  bigdl-core-release-python-pypi:
    runs-on: [self-hosted, ubuntu-20.04-lts, Bree-core]
    needs: llm-cpp-build
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3
      with:
        repository: intel-analytics/BigDL-core
        ref: ${{ env.Branch }}
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.6.3

    - name: Set up Maven Settings
      uses: s4u/maven-settings-action@v2.6.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
            "id": "central",
            "configuration": {
              "httpConfiguration": {
                "all": {
                  "connectionTimeout": "3600000",
                  "readTimeout": "3600000"
                  }
                }
              }
          }]
        mirrors: '[{"id": "ardaNexus", "name": "ardaNexus", "mirrorOf": "*", "url": "${NEXUS_URL}" }]'

    - name: set env 
      env:
        PYPI: '2.2.0b20221206'
        JAR: 'https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/core/dist/all/2.2.0-SNAPSHOT/all-2.2.0-20220919.010507-1.jar'
      run: |
        echo "PYPI_VERSION=${{ github.event.inputs.version || env.PYPI }}" >> $GITHUB_ENV
        echo "JAR_URL=${{ github.event.inputs.jarurl || env.JAR }}" >> $GITHUB_ENV

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install wget -y
        apt-get install zip -y
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
        pip install twine
    - name: Download llm binary
      uses: ./.github/actions/llm/download-llm-binary
    - name: Build package
      run: |
        set -x
        echo ${{ env.PYPI_VERSION }}
        export ORIGINAL_PATH=$PATH
        
        echo ${{ env.JAR_URL }}
        #export JAR_URL=https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/core/dist/all/2.2.0-SNAPSHOT/all-2.2.0-20220919.010507-1.jar
        #export PYPI_VERSION=2.2.0b20221205
        cd python/dev/
        ## linux ##
        bash release_default_linux.sh $JAR_URL $PYPI_VERSION true
        
        ## mac ##
        bash release_default_mac.sh $JAR_URL $PYPI_VERSION true
        
