name: BigDL Release Docker

on:
  #pull_request:
    #branchs: [ main ]
  
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker image tag (e.g. 2.1.0-SNAPSHOT)'
        required: true
        default: 'latest'
        type: string

permissions:
  contents: read

jobs:

  docker-build-bigdl:
    runs-on: [self-hosted, Shire]

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3
    - name: set env
      env:
        DEFAULT_TAG: 'latest'
      run: |
        echo "TAG=${{ github.event.inputs.tag || env.DEFAULT_TAG }}" >> $GITHUB_ENV
    - name: docker login
      run: |
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - name: docker deploy bigdl
      run: |
        export IMAGE=intelanalytics/bigdl
        cd docker/bigdl
        echo "########################################"
        echo "################# bigdl 3.1.3 #######"
        echo "########################################"
        docker build \
          --build-arg http_proxy=${HTTP_PROXY} \
          --build-arg https_proxy=${HTTPS_PROXY} \
          --build-arg SPARK_VERSION=3.1.3 \
          --build-arg JDK_VERSION=8u192 \
          --build-arg JDK_URL=${JDK_URL} \
          --build-arg no_proxy=${NO_PROXY} \
          --rm --no-cache -t $IMAGE-spark-3.1.3:${TAG} .
        docker push ${IMAGE}-spark-3.1.3:${TAG}
        docker tag ${IMAGE}-spark-3.1.3:${TAG} ${IMAGE}:${TAG}
        docker push ${IMAGE}:${TAG}
        docker tag ${IMAGE}:${TAG} 10.239.45.10/arda/${IMAGE}-spark-3.1.3:${TAG}
        docker push 10.239.45.10/arda/${IMAGE}-spark-3.1.3:${TAG}
        docker rmi -f ${IMAGE}-spark-3.1.3:${TAG} 10.239.45.10/arda/${IMAGE}-spark-3.1.3:${TAG}
    - name: docker deploy bigdl-k8s
      run: |
        cd docker/bigdl-k8s
        export IMAGE=intelanalytics/bigdl-k8s
        echo "########################################"
        echo "################# bigdl-k8s 3.1.3 #######"
        echo "########################################"
        docker build \
        --build-arg http_proxy=${HTTP_PROXY} \
        --build-arg https_proxy=${HTTPS_PROXY} \
        --build-arg SPARK_VERSION=3.1.3 \
        --build-arg JDK_VERSION=8u192 \
        --build-arg JDK_URL=${JDK_URL} \
        --build-arg no_proxy=${NO_PROXY} \
        --rm --no-cache -t ${IMAGE}-spark-3.1.3:${TAG} .
        docker push ${IMAGE}-spark-3.1.3:${TAG}
        docker tag ${IMAGE}-spark-3.1.3:${TAG} ${IMAGE}:${TAG}
        docker push ${IMAGE}:${TAG}
        docker tag ${IMAGE}:${TAG} 10.239.45.10/arda/${IMAGE}-spark-3.1.3:${TAG}
        docker push 10.239.45.10/arda/${IMAGE}-spark-3.1.3:${TAG}
        docker rmi -f ${IMAGE}-spark-3.1.3:${TAG}
    - name: docker deploy bigdl-chronos
      run: |
        mv docker/chronos-nightly/Dockerfile ./Dockerfile
        export IMAGE=intelanalytics/bigdl-chronos
        echo "########################################"
        echo "################# bigdl-chronos #######"
        echo "########################################"
        docker build \
        --build-arg http_proxy=${HTTP_PROXY} \
        --build-arg https_proxy=${HTTPS_PROXY} \
        --rm --no-cache -t ${IMAGE}:${TAG} .
        docker push ${IMAGE}:${TAG}
        docker tag ${IMAGE}:${TAG} 10.239.45.10/arda/${IMAGE}:${TAG}
        docker push 10.239.45.10/arda/${IMAGE}:${TAG}
        docker rmi -f ${IMAGE}:${TAG} 10.239.45.10/arda/${IMAGE}:${TAG}
    - name: docker deploy bigdl-orca
      run: |
        cd docker/orca
        export IMAGE=intelanalytics/bigdl-orca
        echo "########################################"
        echo "################# bigdl-orca ###########"
        echo "########################################"
        docker build \
        --build-arg http_proxy=${HTTP_PROXY} \
        --build-arg https_proxy=${HTTPS_PROXY} \
        --build-arg JDK_VERSION=8u192 \
        --build-arg JDK_URL=${JDK_URL} \
        --build-arg no_proxy=${NO_PROXY} \
        --build-arg SPARK_VERSION=3.1.3 \
        --build-arg PY4J_VERSION=0.10.9 \
        --rm --no-cache -t ${IMAGE}:${TAG} .
        # tag 'latest'
        docker push ${IMAGE}:${TAG}
        docker tag ${IMAGE}:${TAG} 10.239.45.10/arda/${IMAGE}:${TAG}
        docker push 10.239.45.10/arda/${IMAGE}:${TAG}
        docker rmi -f ${IMAGE}:${TAG} 10.239.45.10/arda/${IMAGE}:${TAG}

    - name: docker deploy bigdl-friesian
      run: |
        cd docker/friesian-serving
        export IMAGE=intelanalytics/friesian-serving
        export FTP_URI=http://10.239.45.10:8081/repository/raw
        echo "################################################"
        echo "################# friesian serving 3.1.3 #######"
        echo "################################################"
        wget $FTP_URI/analytics-zoo-data/faiss-lib.zip
        wget $FTP_URI/analytics-zoo-data/jersey.tar.gz
        unzip -o faiss-lib.zip -d lib
        tar xzvf jersey.tar.gz
        docker build \
        --build-arg http_proxy=${HTTP_PROXY} \
        --build-arg https_proxy=${HTTPS_PROXY} \
        --build-arg SPARK_VERSION=3.1.3 \
        --build-arg no_proxy=${NO_PROXY} \
        --rm --no-cache -t $IMAGE:${TAG} .
        docker push $IMAGE:${TAG}
        docker tag "${IMAGE}:${TAG}" "10.239.45.10/arda/$IMAGE:${TAG}"
        docker push 10.239.45.10/arda/${IMAGE}:${TAG}
        docker rmi -f ${IMAGE}:${TAG} 10.239.45.10/arda/${IMAGE}:${TAG}
        rm -rf lib faiss-lib.zip
        rm -rf jersey jersey.tar.gz


