name: BigDL Release Pypi

on:
  #pull_request:
  
  workflow_dispatch:

permissions:
  contents: read

jobs:
  llm-cpp-build:
    uses: ./.github/workflows/llm-binary-build.yml
  bigdl-release-python-pypi:
    runs-on: [self-hosted, ubuntu-20.04-lts, Bree]
    # if: ${{ github.actor == 'Le-Zheng' }}
    needs: llm-cpp-build
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action

    - name: Set up maven
      uses: ./.github/actions/maven-setup-action

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
        pip install twine
    - name: Download llm binary
      uses: ./.github/actions/llm/download-llm-binary    
    - name: Build package
      run: |
        export TIMESTAMP=`date '+%Y%m%d'`
        export PYPI_VERSION=$(cat ./python/version.txt | head -1)
        echo ${PYPI_VERSION}
        nb_version=${PYPI_VERSION}
        #nb_version=${PYPI_VERSION}b${TIMESTAMP}1
        echo ${nb_version}

        ## windows ##
        bash python/dev/release_default_windows.sh ${nb_version} false true

        ## linux ##
        bash python/dev/release_default_linux.sh ${nb_version} true

        ## mac ##
        bash python/dev/release_default_mac.sh ${nb_version} true
